{% set name = "financetoolkit" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/financetoolkit-{{ version }}.tar.gz
  sha256: 43e0821389f043770ac4aea8f5d9a1fff20ae178266560cf53209ea2b2c7feca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - setuptools <65.5.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - pandas >=2.0.0,<3.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - financetoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JerBouma/FinanceToolkit
  summary: Transparent and Efficient Financial Analysis
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
