{% set name = "financetoolkit" %}
{% set version = "2.0.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/financetoolkit-{{ version }}.tar.gz
  sha256: 5665e8ee51f09fc31df68be1fa8383ffdd684a8004241474fe87f6a9406736ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools <65.5.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.2.0,<3.0.0
    - requests >=2.32.3,<3.0.0
    - scikit-learn >=1.5.0,<2.0.0

    # For pandas[computation]
    - scipy >=1.10.0
    - xarray >=2022.12.0

    # For pandas[performance]
    - bottleneck >=1.3.6
    - numba >=0.56.4
    - numexpr >=2.8.4

    # For pandas[plot]
    - matplotlib-base >=3.6.3

    # For pandas[excel]
    - odfpy >=1.4.1
    - openpyxl >=3.1.0
    - python-calamine >=0.1.7
    - pyxlsb >=1.0.10
    - xlrd >=2.0.1
    - xlsxwriter >=3.0.5

    # Not listed but required
    - pyyaml
    - tqdm

test:
  imports:
    - financetoolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JerBouma/FinanceToolkit
  summary: Transparent and Efficient Financial Analysis
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
