{% set name = "financetoolkit" %}
{% set version = "1.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/financetoolkit-{{ version }}.tar.gz
  sha256: 3bbd3280a4e08181f5b2fd4b5579045fd79872369f31ba41839dc7a6745e5482

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools <65.5.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10,<3.13
    - pandas >=2.2.0,<3.0.0
    - requests >=2.31.0,<3.0.0
    - scikit-learn >=1.3.0,<2.0.0

    # For pandas[computation]
    - scipy >=1.10.0
    - xarray >=2022.12.0

    # For pandas[performance]
    - bottleneck >=1.3.6
    - numba >=0.56.4
    - numexpr >=2.8.4

    # For pandas[plot]
    - matplotlib-base >=3.6.3

test:
  imports:
    - financetoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JerBouma/FinanceToolkit
  summary: Transparent and Efficient Financial Analysis
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
