schema_version: 1

context:
  name: financetoolkit
  version: 2.0.4
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/financetoolkit-${{ version }}.tar.gz
  sha256: 6f12217fa4e40cf8122ad4bad968589c5b366f140c580b7af525b853365f03ef

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=2.2.0,<3.0.0
    - scikit-learn >=1.6.0,<2.0.0
    - requests >=2.32.3,<3.0.0
    - yfinance
    - openpyxl >=3.1.0,<4.0.0
    - tqdm >=4.67.0,<5.0.0
    # For pandas[computation]
    - scipy >=1.10.0
    - xarray >=2022.12.0
    # For pandas[performance]
    - bottleneck >=1.3.6
    - numba >=0.56.4
    - numexpr >=2.8.4
    # For pandas[plot]
    - matplotlib-base >=3.6.3
    # For pandas[excel]
    - odfpy >=1.4.1
    # openpyxl >=3.1.0 already listed above
    - python-calamine >=0.1.7
    - pyxlsb >=1.0.10
    - xlrd >=2.0.1
    - xlsxwriter >=3.0.5
    # Not listed but required
    - pyyaml

tests:
  - python:
      imports:
        - financetoolkit
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Transparent and Efficient Financial Analysis
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/JerBouma/FinanceToolkit

extra:
  recipe-maintainers:
    - thewchan
